---

- hosts: all
  become: yes
  tasks:
  -  name: CentOS Install Zabbix-agent
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        web systemd
  -  name: Ubuntu Install Zabbix-agent
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Ubuntu"
     notify:
        web systemd
  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent
     enabled: yes
     state: started

